import { NextResponse } from "next/server";
import { createAdminClient } from "@/lib/supabase/server";
export async function GET(request:Request){
 if(!process.env.CRON_SECRET||request.headers.get("authorization")!==`Bearer ${process.env.CRON_SECRET}`)return NextResponse.json({error:"Unauthorized"},{status:401});
 const s=createAdminClient();const {data:run}=await s.from("cbg_maintenance_runs").insert({status:"running"}).select("id").single();
 try{const now=new Date();const [{data:overdue,error},{data:staleAppeals},{data:failedEvaluations},{data:fairnessAlerts}]=await Promise.all([
  s.from("cbg_applications").select("id,reference_number,assigned_to").lt("due_at",now.toISOString()).not("status","in",'(decided,closed)').not("assigned_to","is",null),
  s.from("cbg_appeals").select("id,assigned_to").in("status",["open","under_review"]).lt("submitted_at",new Date(now.getTime()-7*86400000).toISOString()).not("assigned_to","is",null),
  s.from("cbg_model_evaluations").select("id,authorized_by").eq("status","failed").gte("completed_at",new Date(now.getTime()-86400000).toISOString()),
  s.from("cbg_fairness_alerts").select("id,title,assigned_to").in("status",["open","investigating"]).not("assigned_to","is",null)
 ]);if(error)throw error;
 const notifications=[...(overdue??[]).map(x=>({user_id:x.assigned_to,kind:"case_overdue",title:"Case is overdue",body:`${x.reference_number} requires attention.`,entity_type:"application",entity_id:x.id})),...(staleAppeals??[]).map(x=>({user_id:x.assigned_to,kind:"appeal_overdue",title:"Appeal review is overdue",body:"An assigned appeal has been open for more than seven days.",entity_type:"appeal",entity_id:x.id})),...(failedEvaluations??[]).map(x=>({user_id:x.authorized_by,kind:"evaluation_failed",title:"Model evaluation failed",body:"Review the evaluation before another governance action.",entity_type:"model_evaluation",entity_id:x.id})),...(fairnessAlerts??[]).map(x=>({user_id:x.assigned_to,kind:"fairness_investigation",title:"Fairness investigation requires attention",body:x.title,entity_type:"fairness_alert",entity_id:x.id}))];
 let created=0;for(const n of notifications){const {data:existing}=await s.from("cbg_notifications").select("id").eq("user_id",n.user_id).eq("kind",n.kind).eq("entity_id",n.entity_id).is("read_at",null).maybeSingle();if(!existing){const {error:e}=await s.from("cbg_notifications").insert(n);if(!e)created++;}}
 const {data:fairness,error:fairnessError}=await s.rpc("cbg_compute_fairness_metrics",{p_period_start:new Date(now.getTime()-30*86400000).toISOString().slice(0,10),p_period_end:now.toISOString().slice(0,10)});if(fairnessError)throw fairnessError;
 const checks={overdue_cases:(overdue??[]).length,stale_appeals:(staleAppeals??[]).length,failed_evaluations:(failedEvaluations??[]).length,open_fairness_alerts:(fairnessAlerts??[]).length,notifications_created:created,fairness_groups:fairness};if(run)await s.from("cbg_maintenance_runs").update({status:"succeeded",checks,completed_at:new Date().toISOString()}).eq("id",run.id);return NextResponse.json({ok:true,...checks});
 }catch(cause){const message=cause instanceof Error?cause.message.slice(0,300):"Maintenance failed";console.error(JSON.stringify({level:"error",operation:"scheduled_maintenance",message}));if(run)await s.from("cbg_maintenance_runs").update({status:"failed",safe_error:message,completed_at:new Date().toISOString()}).eq("id",run.id);return NextResponse.json({error:"Maintenance failed safely"},{status:500});}
}
