begin;
create extension if not exists pgcrypto;
create type public.app_role as enum ('intake_officer','medical_verification_officer','social_financial_assessment_officer','case_review_committee','human_oversight_committee','appeals_reviewer','admin');
create type public.application_status as enum ('draft','submitted','medical_verification','social_assessment','verified','assessment_ready','human_review','decision_pending','decided','appealed','closed');
create type public.version_status as enum ('draft','evaluation','approved','active','retired','rolled_back');
create type public.decision_kind as enum ('approve','modify','refer','reject');

create table public.users(id uuid primary key references auth.users(id) on delete restrict,display_name text not null,email text not null,active boolean not null default true,last_login_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.roles(id uuid primary key default gen_random_uuid(),name public.app_role unique not null,description text not null,created_at timestamptz not null default now());
create table public.user_roles(user_id uuid references public.users(id) on delete cascade,role_id uuid references public.roles(id) on delete restrict,assigned_by uuid references public.users(id),assigned_at timestamptz not null default now(),primary key(user_id,role_id));
create table public.applications(id uuid primary key default gen_random_uuid(),reference_number text unique not null,applicant_user_id uuid,assigned_to uuid references public.users(id),status public.application_status not null default 'submitted',parish text not null,rural boolean not null default false,consent_status text not null check(consent_status in('granted','withdrawn','pending')),consent_recorded_at timestamptz,consent_version text,submitted_at timestamptz not null default now(),retention_until date,legal_hold boolean not null default false,created_by uuid references public.users(id),updated_by uuid references public.users(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.applicant_profiles(application_id uuid primary key references public.applications(id) on delete cascade,full_name text not null,date_of_birth date not null,gender text,phone text,address text,disability_status boolean not null default false,insurance_status text,employment_status text,caregiving_responsibilities boolean not null default false,existing_welfare_support boolean not null default false,created_by uuid references public.users(id),updated_by uuid references public.users(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.medical_verifications(id uuid primary key default gen_random_uuid(),application_id uuid unique not null references public.applications(id) on delete cascade,urgency_score smallint not null check(urgency_score between 0 and 30),summary text not null,documents_complete boolean not null,verified_by uuid not null references public.users(id),verified_at timestamptz not null default now(),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.social_assessments(id uuid primary key default gen_random_uuid(),application_id uuid unique not null references public.applications(id) on delete cascade,financial_hardship_score smallint not null check(financial_hardship_score between 0 and 20),access_barrier_score smallint not null check(access_barrier_score between 0 and 20),unmet_need_score smallint not null check(unmet_need_score between 0 and 15),vulnerability_score smallint not null check(vulnerability_score between 0 and 10),support_gap_score smallint not null check(support_gap_score between 0 and 5),missed_appointments boolean not null default false,transport_difficulty boolean not null default false,family_support_available boolean,summary text not null,assessed_by uuid not null references public.users(id),assessed_at timestamptz not null default now(),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.model_versions(id uuid primary key default gen_random_uuid(),version text unique not null,status public.version_status not null default 'draft',rules jsonb not null,change_summary text not null,previous_version_id uuid references public.model_versions(id),created_by uuid not null references public.users(id),approved_by uuid references public.users(id),approved_at timestamptz,activated_by uuid references public.users(id),activated_at timestamptz,rollback_of uuid references public.model_versions(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create unique index one_active_model_version on public.model_versions(status) where status='active';
create table public.ai_assessments(id uuid primary key default gen_random_uuid(),application_id uuid not null references public.applications(id) on delete restrict,model_version_id uuid not null references public.model_versions(id),score smallint not null check(score between 0 and 100),category text not null,confidence numeric(5,2) not null check(confidence between 0 and 100),reasons jsonb not null default '[]',risk_factors jsonb not null default '[]',missing_information jsonb not null default '[]',fairness_warnings jsonb not null default '[]',recommended_action text not null,review_pathway text not null,requires_human_review boolean not null default true check(requires_human_review=true),input_snapshot jsonb not null,created_by uuid not null references public.users(id),created_at timestamptz not null default now());
create table public.human_reviews(id uuid primary key default gen_random_uuid(),application_id uuid not null references public.applications(id) on delete restrict,ai_assessment_id uuid not null references public.ai_assessments(id),reviewer_id uuid not null references public.users(id),reviewer_role public.app_role not null,disposition text not null check(disposition in('agree','modify','override')),proposed_decision public.decision_kind not null,final_score smallint check(final_score between 0 and 100),final_category text,evidence_considered text not null,factors_changed jsonb not null default '[]',explanation text not null,conflict_of_interest boolean not null default false,reviewed_at timestamptz not null default now(),created_at timestamptz not null default now());
create table public.final_decisions(id uuid primary key default gen_random_uuid(),application_id uuid unique not null references public.applications(id),human_review_id uuid not null references public.human_reviews(id),decision public.decision_kind not null,explanation text not null,decided_by uuid not null references public.users(id),decided_at timestamptz not null default now(),case_outcome text,created_at timestamptz not null default now());
create table public.human_corrections(id uuid primary key default gen_random_uuid(),application_id uuid not null references public.applications(id),human_review_id uuid not null references public.human_reviews(id),category text not null check(category in('medical_urgency_underestimated','rural_transport_misunderstood','missed_appointments_unfair','disability_overlooked','caregiving_overlooked','medication_costs_underestimated','family_support_overlooked','support_gap_misunderstood','referral_too_quick','ai_correct','human_reviewer_error','policy_unclear','insufficient_information')),override_reason text not null,bias_concern boolean not null default false,policy_gap boolean not null default false,created_by uuid not null references public.users(id),created_at timestamptz not null default now());
create table public.appeals(id uuid primary key default gen_random_uuid(),application_id uuid not null references public.applications(id),reason text not null,evidence jsonb not null default '[]',status text not null default 'open' check(status in('open','under_review','decided','withdrawn')),submitted_at timestamptz not null default now(),assigned_to uuid references public.users(id),created_by uuid references public.users(id),updated_at timestamptz not null default now());
create table public.appeal_decisions(id uuid primary key default gen_random_uuid(),appeal_id uuid unique not null references public.appeals(id),outcome text not null check(outcome in('upheld','modified','overturned','more_information')),explanation text not null,decided_by uuid not null references public.users(id),decided_at timestamptz not null default now());
create table public.correction_patterns(id uuid primary key default gen_random_uuid(),correction_category text not null,affected_group text,occurrence_count integer not null check(occurrence_count>0),first_seen_at timestamptz not null,last_seen_at timestamptz not null,status text not null default 'observed',analysis jsonb not null default '{}',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.policy_proposals(id uuid primary key default gen_random_uuid(),pattern_id uuid references public.correction_patterns(id),title text not null,problem_statement text not null,proposed_change text not null,evidence_summary text not null,status text not null default 'draft' check(status in('draft','committee_review','approved','rejected','implemented')),submitted_by uuid not null references public.users(id),committee_decision_by uuid references public.users(id),committee_decision_at timestamptz,committee_reason text,conflict_disclosures jsonb not null default '[]',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.fairness_metrics(id uuid primary key default gen_random_uuid(),period_start date not null,period_end date not null,dimension text not null,dimension_value text not null,model_version_id uuid references public.model_versions(id),case_count integer not null,agreement_rate numeric(5,2),override_rate numeric(5,2),appeal_success_rate numeric(5,2),average_confidence numeric(5,2),incorrectly_deprioritized integer not null default 0,unresolved_reviews integer not null default 0,average_decision_hours numeric(10,2),computed_at timestamptz not null default now());
create table public.fairness_alerts(id uuid primary key default gen_random_uuid(),metric_id uuid references public.fairness_metrics(id),severity text not null check(severity in('low','medium','high')),title text not null,investigation_question text not null,status text not null default 'open' check(status in('open','investigating','resolved','dismissed')),finding text,assigned_to uuid references public.users(id),resolved_by uuid references public.users(id),resolved_at timestamptz,created_at timestamptz not null default now());
create table public.model_evaluations(id uuid primary key default gen_random_uuid(),model_version_id uuid not null references public.model_versions(id),dataset_name text not null,dataset_version text not null,status text not null default 'queued' check(status in('queued','running','passed','failed','cancelled')),baseline_version_id uuid not null references public.model_versions(id),summary jsonb not null default '{}',authorized_by uuid not null references public.users(id),started_at timestamptz,completed_at timestamptz,created_at timestamptz not null default now());
create table public.evaluation_results(id uuid primary key default gen_random_uuid(),evaluation_id uuid not null references public.model_evaluations(id) on delete cascade,case_reference_hash text not null,before_score smallint,before_category text,after_score smallint,after_category text,expected_category text,regression boolean not null default false,details jsonb not null default '{}',created_at timestamptz not null default now());
create table public.deployment_approvals(id uuid primary key default gen_random_uuid(),model_version_id uuid not null references public.model_versions(id),evaluation_id uuid not null references public.model_evaluations(id),decision text not null check(decision in('approve','reject','rollback')),reason text not null,evidence_considered text not null,conflict_of_interest boolean not null,approver_id uuid not null references public.users(id),approved_at timestamptz not null default now());
create table public.audit_logs(id bigint generated always as identity primary key,actor_id uuid references public.users(id),actor_role public.app_role,action text not null,entity_type text not null,entity_id text,metadata jsonb not null default '{}',ip_hash text,user_agent_hash text,occurred_at timestamptz not null default now());

create index applications_status_idx on public.applications(status,submitted_at);create index ai_assessments_application_idx on public.ai_assessments(application_id,created_at desc);create index human_reviews_application_idx on public.human_reviews(application_id,reviewed_at desc);create index corrections_category_idx on public.human_corrections(category,created_at);create index appeals_status_idx on public.appeals(status,submitted_at);create index fairness_metric_dimension_idx on public.fairness_metrics(dimension,period_end);create index audit_entity_idx on public.audit_logs(entity_type,entity_id,occurred_at desc);create index audit_actor_idx on public.audit_logs(actor_id,occurred_at desc);

insert into public.roles(name,description) values ('intake_officer','Application intake'),('medical_verification_officer','Medical evidence verification'),('social_financial_assessment_officer','Social and financial verification'),('case_review_committee','Qualified case review'),('human_oversight_committee','Policy and model governance'),('appeals_reviewer','Independent appeals review'),('admin','System administration');

create schema if not exists private;
create function private.has_role(required public.app_role) returns boolean language sql stable security definer set search_path='' as $$select exists(select 1 from public.user_roles ur join public.roles r on r.id=ur.role_id join public.users u on u.id=ur.user_id where ur.user_id=(select auth.uid()) and r.name=required and u.active)$$;
revoke all on function private.has_role(public.app_role) from public,anon;grant usage on schema private to authenticated;grant execute on function private.has_role(public.app_role) to authenticated;
create function private.is_case_worker() returns boolean language sql stable security definer set search_path='' as $$select private.has_role('intake_officer') or private.has_role('medical_verification_officer') or private.has_role('social_financial_assessment_officer') or private.has_role('case_review_committee') or private.has_role('human_oversight_committee') or private.has_role('appeals_reviewer') or private.has_role('admin')$$;revoke all on function private.is_case_worker() from public,anon;grant execute on function private.is_case_worker() to authenticated;

alter table public.users enable row level security;alter table public.roles enable row level security;alter table public.user_roles enable row level security;alter table public.applications enable row level security;alter table public.applicant_profiles enable row level security;alter table public.medical_verifications enable row level security;alter table public.social_assessments enable row level security;alter table public.ai_assessments enable row level security;alter table public.human_reviews enable row level security;alter table public.final_decisions enable row level security;alter table public.human_corrections enable row level security;alter table public.appeals enable row level security;alter table public.appeal_decisions enable row level security;alter table public.correction_patterns enable row level security;alter table public.policy_proposals enable row level security;alter table public.fairness_metrics enable row level security;alter table public.fairness_alerts enable row level security;alter table public.model_versions enable row level security;alter table public.model_evaluations enable row level security;alter table public.evaluation_results enable row level security;alter table public.deployment_approvals enable row level security;alter table public.audit_logs enable row level security;
create policy self_user_read on public.users for select to authenticated using(id=(select auth.uid()) or private.has_role('admin'));create policy roles_read on public.roles for select to authenticated using(true);create policy own_roles_read on public.user_roles for select to authenticated using(user_id=(select auth.uid()) or private.has_role('admin'));
create policy case_workers_read_applications on public.applications for select to authenticated using(private.is_case_worker());create policy intake_manage_applications on public.applications for all to authenticated using(private.has_role('intake_officer') or private.has_role('admin')) with check(private.has_role('intake_officer') or private.has_role('admin'));create policy case_workers_read_profiles on public.applicant_profiles for select to authenticated using(private.is_case_worker());create policy intake_manage_profiles on public.applicant_profiles for all to authenticated using(private.has_role('intake_officer') or private.has_role('admin')) with check(private.has_role('intake_officer') or private.has_role('admin'));
create policy medical_read on public.medical_verifications for select to authenticated using(private.is_case_worker());create policy medical_write on public.medical_verifications for all to authenticated using(private.has_role('medical_verification_officer') or private.has_role('admin')) with check(private.has_role('medical_verification_officer') or private.has_role('admin'));create policy social_read on public.social_assessments for select to authenticated using(private.is_case_worker());create policy social_write on public.social_assessments for all to authenticated using(private.has_role('social_financial_assessment_officer') or private.has_role('admin')) with check(private.has_role('social_financial_assessment_officer') or private.has_role('admin'));
create policy assessment_read on public.ai_assessments for select to authenticated using(private.is_case_worker());create policy assessment_create on public.ai_assessments for insert to authenticated with check((private.has_role('case_review_committee') or private.has_role('human_oversight_committee') or private.has_role('admin')) and created_by=(select auth.uid()));create policy reviews_read on public.human_reviews for select to authenticated using(private.is_case_worker());create policy reviews_create on public.human_reviews for insert to authenticated with check((private.has_role('case_review_committee') or private.has_role('human_oversight_committee') or private.has_role('appeals_reviewer')) and reviewer_id=(select auth.uid()));create policy decisions_read on public.final_decisions for select to authenticated using(private.is_case_worker());create policy decisions_create on public.final_decisions for insert to authenticated with check((private.has_role('case_review_committee') or private.has_role('appeals_reviewer')) and decided_by=(select auth.uid()));
create policy corrections_read on public.human_corrections for select to authenticated using(private.is_case_worker());create policy corrections_create on public.human_corrections for insert to authenticated with check(private.is_case_worker() and created_by=(select auth.uid()));create policy appeals_read on public.appeals for select to authenticated using(private.is_case_worker());create policy appeals_manage on public.appeals for all to authenticated using(private.has_role('appeals_reviewer') or private.has_role('admin')) with check(private.has_role('appeals_reviewer') or private.has_role('admin'));create policy appeal_decisions_manage on public.appeal_decisions for all to authenticated using(private.has_role('appeals_reviewer') or private.has_role('admin')) with check((private.has_role('appeals_reviewer') or private.has_role('admin')) and decided_by=(select auth.uid()));
create policy governance_read_patterns on public.correction_patterns for select to authenticated using(private.has_role('human_oversight_committee') or private.has_role('admin'));create policy governance_manage_proposals on public.policy_proposals for all to authenticated using(private.has_role('human_oversight_committee') or private.has_role('admin')) with check(private.has_role('human_oversight_committee') or private.has_role('admin'));create policy metrics_read on public.fairness_metrics for select to authenticated using(private.is_case_worker());create policy alerts_read on public.fairness_alerts for select to authenticated using(private.is_case_worker());create policy alerts_manage on public.fairness_alerts for all to authenticated using(private.has_role('human_oversight_committee') or private.has_role('admin')) with check(private.has_role('human_oversight_committee') or private.has_role('admin'));
create policy versions_read on public.model_versions for select to authenticated using(private.is_case_worker());create policy versions_manage on public.model_versions for all to authenticated using(private.has_role('human_oversight_committee') or private.has_role('admin')) with check(private.has_role('human_oversight_committee') or private.has_role('admin'));create policy evaluations_manage on public.model_evaluations for all to authenticated using(private.has_role('human_oversight_committee') or private.has_role('admin')) with check(private.has_role('human_oversight_committee') or private.has_role('admin'));create policy results_read on public.evaluation_results for select to authenticated using(private.has_role('human_oversight_committee') or private.has_role('admin'));create policy approvals_manage on public.deployment_approvals for all to authenticated using(private.has_role('human_oversight_committee') or private.has_role('admin')) with check((private.has_role('human_oversight_committee') or private.has_role('admin')) and approver_id=(select auth.uid()));create policy audit_read on public.audit_logs for select to authenticated using(private.has_role('human_oversight_committee') or private.has_role('admin'));create policy audit_insert on public.audit_logs for insert to authenticated with check(actor_id=(select auth.uid()));

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('case-documents','case-documents',false,10485760,array['application/pdf','image/jpeg','image/png']) on conflict(id) do nothing;create policy case_document_read on storage.objects for select to authenticated using(bucket_id='case-documents' and private.is_case_worker());create policy case_document_insert on storage.objects for insert to authenticated with check(bucket_id='case-documents' and (private.has_role('intake_officer') or private.has_role('medical_verification_officer') or private.has_role('social_financial_assessment_officer') or private.has_role('admin')));

create function private.block_ai_final_decision() returns trigger language plpgsql set search_path='' as $$begin if new.human_review_id is null then raise exception 'AI-only final decisions are prohibited';end if;if not exists(select 1 from public.human_reviews h where h.id=new.human_review_id and h.application_id=new.application_id and h.reviewer_id is not null and length(h.explanation)>=20) then raise exception 'A valid explained human review is required';end if;return new;end$$;create trigger enforce_human_final_decision before insert or update on public.final_decisions for each row execute function private.block_ai_final_decision();
create function private.protect_active_version() returns trigger language plpgsql set search_path='' as $$begin if new.status='active' then if not exists(select 1 from public.deployment_approvals d join public.model_evaluations e on e.id=d.evaluation_id where d.model_version_id=new.id and d.decision='approve' and d.conflict_of_interest=false and e.status='passed') then raise exception 'Passed evaluation and conflict-free committee approval required';end if;new.activated_by=(select auth.uid());new.activated_at=now();end if;return new;end$$;create trigger enforce_version_activation before update of status on public.model_versions for each row execute function private.protect_active_version();
create function private.prevent_audit_mutation() returns trigger language plpgsql as $$begin raise exception 'Audit records are append-only';end$$;create trigger audit_append_only before update or delete on public.audit_logs for each row execute function private.prevent_audit_mutation();

create function public.submit_human_review(p_application_id uuid,p_assessment_id uuid,p_disposition text,p_decision public.decision_kind,p_final_score smallint,p_final_category text,p_evidence text,p_explanation text,p_correction_category text,p_reviewer_role public.app_role) returns uuid language plpgsql security invoker set search_path='' as $$declare review_id uuid;begin if length(p_evidence)<20 or length(p_explanation)<20 then raise exception 'Evidence and explanation are required';end if;insert into public.human_reviews(application_id,ai_assessment_id,reviewer_id,reviewer_role,disposition,proposed_decision,final_score,final_category,evidence_considered,explanation) values(p_application_id,p_assessment_id,(select auth.uid()),p_reviewer_role,p_disposition,p_decision,p_final_score,p_final_category,p_evidence,p_explanation) returning id into review_id;insert into public.final_decisions(application_id,human_review_id,decision,explanation,decided_by) values(p_application_id,review_id,p_decision,p_explanation,(select auth.uid()));insert into public.human_corrections(application_id,human_review_id,category,override_reason,created_by) values(p_application_id,review_id,p_correction_category,p_explanation,(select auth.uid()));update public.applications set status='decided',updated_by=(select auth.uid()),updated_at=now() where id=p_application_id;insert into public.audit_logs(actor_id,actor_role,action,entity_type,entity_id,metadata) values((select auth.uid()),p_reviewer_role,'human_review_completed','application',p_application_id::text,jsonb_build_object('disposition',p_disposition,'decision',p_decision));return review_id;end$$;revoke all on function public.submit_human_review(uuid,uuid,text,public.decision_kind,smallint,text,text,text,text,public.app_role) from public,anon;grant execute on function public.submit_human_review(uuid,uuid,text,public.decision_kind,smallint,text,text,text,text,public.app_role) to authenticated;

grant usage on schema public to authenticated;grant select,insert,update on all tables in schema public to authenticated;revoke delete on public.audit_logs,public.ai_assessments,public.human_reviews,public.final_decisions,public.deployment_approvals from authenticated;grant usage,select on all sequences in schema public to authenticated;
commit;
