"use server";
import { revalidatePath } from "next/cache";
import { z } from "zod";
import { requireActor } from "@/lib/auth";
import { createClient } from "@/lib/supabase/server";
import { createAdminClient } from "@/lib/supabase/server";
import { createHash } from "node:crypto";
import { evaluationDatasetSchema, evaluateCase } from "@/lib/evaluation";

const proposal = z.object({ title:z.string().min(5).max(160), problem:z.string().min(20).max(5000), change:z.string().min(20).max(5000), evidence:z.string().min(20).max(5000), patternId:z.union([z.literal(""),z.uuid()]) });
export async function createProposal(fd:FormData){const actor=await requireActor(["human_oversight_committee","admin"]);const p=proposal.safeParse(Object.fromEntries(fd));if(!p.success)throw new Error("Proposal is incomplete");const s=await createClient();const {error}=await s.from("cbg_policy_proposals").insert({pattern_id:p.data.patternId||null,title:p.data.title,problem_statement:p.data.problem,proposed_change:p.data.change,evidence_summary:p.data.evidence,status:"committee_review",submitted_by:actor.id});if(error)throw error;revalidatePath("/dashboard/governance")}

const decision=z.object({proposalId:z.uuid(),decision:z.enum(["approved","rejected"]),reason:z.string().min(20).max(5000),conflict:z.string().optional()});
export async function decideProposal(fd:FormData){const actor=await requireActor(["human_oversight_committee"]);const p=decision.safeParse(Object.fromEntries(fd));if(!p.success||p.data.conflict==="on")throw new Error("A conflict-free explained decision is required");const s=await createClient();const {error}=await s.from("cbg_policy_proposals").update({status:p.data.decision,committee_decision_by:actor.id,committee_decision_at:new Date().toISOString(),committee_reason:p.data.reason}).eq("id",p.data.proposalId);if(error)throw error;await s.from("cbg_audit_logs").insert({actor_id:actor.id,actor_role:"human_oversight_committee",action:"policy_proposal_decided",entity_type:"policy_proposal",entity_id:p.data.proposalId,metadata:{decision:p.data.decision}});revalidatePath("/dashboard/governance")}

export async function refreshPatterns(){await requireActor(["human_oversight_committee","admin"]);const s=await createClient();const {error}=await s.rpc("cbg_refresh_correction_patterns");if(error)throw error;revalidatePath("/dashboard/governance")}

const activation=z.object({versionId:z.uuid(),evaluationId:z.uuid(),reason:z.string().min(20).max(5000),evidence:z.string().min(20).max(5000),conflict:z.string().optional()});
export async function activateVersion(fd:FormData){await requireActor(["human_oversight_committee"]);const p=activation.safeParse(Object.fromEntries(fd));if(!p.success)throw new Error("Activation approval is incomplete");const s=await createClient();const {error}=await s.rpc("cbg_activate_version",{p_version_id:p.data.versionId,p_evaluation_id:p.data.evaluationId,p_reason:p.data.reason,p_evidence:p.data.evidence,p_conflict:p.data.conflict==="on"});if(error)throw error;revalidatePath("/dashboard/governance")}

const rollback=z.object({currentId:z.uuid(),targetId:z.uuid(),reason:z.string().min(20).max(5000)});
export async function rollbackVersion(fd:FormData){await requireActor(["human_oversight_committee"]);const p=rollback.safeParse(Object.fromEntries(fd));if(!p.success)throw new Error("Rollback request is incomplete");const s=await createClient();const {error}=await s.rpc("cbg_rollback_version",{p_current_id:p.data.currentId,p_target_id:p.data.targetId,p_reason:p.data.reason});if(error)throw error;revalidatePath("/dashboard/governance")}

export async function uploadEvaluationDataset(fd:FormData){const actor=await requireActor(["human_oversight_committee","admin"]);const file=fd.get("dataset");if(!(file instanceof File)||file.size>2*1024*1024||file.type!=="application/json")throw new Error("Upload a JSON dataset no larger than 2 MB");const parsed=evaluationDatasetSchema.safeParse(JSON.parse(await file.text()));if(!parsed.success)throw new Error("Dataset format is invalid");const admin=createAdminClient();const rows=parsed.data.cases.map(c=>({dataset_name:parsed.data.name,dataset_version:parsed.data.version,case_reference_hash:createHash("sha256").update(c.reference).digest("hex"),input_snapshot:c.input,expected_category:c.expectedCategory,authorized_by:actor.id}));const {error}=await admin.from("cbg_evaluation_cases").upsert(rows,{onConflict:"dataset_name,dataset_version,case_reference_hash"});if(error)throw error;const s=await createClient();await s.from("cbg_audit_logs").insert({actor_id:actor.id,actor_role:actor.roles[0],action:"evaluation_dataset_uploaded",entity_type:"evaluation_dataset",entity_id:`${parsed.data.name}:${parsed.data.version}`,metadata:{case_count:rows.length}});revalidatePath("/dashboard/governance")}

const runSchema=z.object({versionId:z.uuid(),baselineId:z.uuid(),datasetName:z.string().min(1),datasetVersion:z.string().min(1)});
export async function runEvaluation(fd:FormData){const actor=await requireActor(["human_oversight_committee","admin"]);const p=runSchema.parse(Object.fromEntries(fd));const admin=createAdminClient();const [{data:versions},{data:cases}]=await Promise.all([admin.from("cbg_model_versions").select("id,rules").in("id",[p.versionId,p.baselineId]),admin.from("cbg_evaluation_cases").select("case_reference_hash,input_snapshot,expected_category").eq("dataset_name",p.datasetName).eq("dataset_version",p.datasetVersion)]);if(!versions?.length||!cases?.length)throw new Error("Version or dataset not found");const after=versions.find(v=>v.id===p.versionId)?.rules??{};const before=versions.find(v=>v.id===p.baselineId)?.rules??{};const {data:evaluation,error}=await admin.from("cbg_model_evaluations").insert({model_version_id:p.versionId,baseline_version_id:p.baselineId,dataset_name:p.datasetName,dataset_version:p.datasetVersion,status:"running",authorized_by:actor.id,started_at:new Date().toISOString()}).select("id").single();if(error||!evaluation)throw error??new Error("Evaluation could not start");const results=cases.map(c=>{const r=evaluateCase(c.input_snapshot as never,c.expected_category,before as never,after as never);return {evaluation_id:evaluation.id,case_reference_hash:c.case_reference_hash,before_score:r.score,before_category:r.before,after_score:r.score,after_category:r.after,expected_category:r.expected,regression:r.regression,details:{improved:r.improved}}});const regressions=results.filter(r=>r.regression).length;const accuracy=results.filter(r=>r.after_category===r.expected_category).length/results.length;const {error:resultError}=await admin.from("cbg_evaluation_results").insert(results);if(resultError)throw resultError;await admin.from("cbg_model_evaluations").update({status:regressions===0?"passed":"failed",completed_at:new Date().toISOString(),summary:{case_count:results.length,regressions,accuracy:Math.round(accuracy*10000)/100}}).eq("id",evaluation.id);const s=await createClient();await s.from("cbg_audit_logs").insert({actor_id:actor.id,actor_role:actor.roles[0],action:"model_evaluation_completed",entity_type:"model_evaluation",entity_id:evaluation.id,metadata:{regressions,case_count:results.length}});revalidatePath("/dashboard/governance")}
